services:

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api

    ports:
      - 3306:3306
  api:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000
